=== xAkre/jmdict.js/src/__tests__/data/xml/originalDtd.dtd
<!ELEMENT JMdict (entry*)>
<!ELEMENT entry (ent_seq, k_ele*, r_ele+, sense+)>
<!ELEMENT ent_seq (#PCDATA)>
<!ELEMENT k_ele (keb, ke_inf*, ke_pri*)>
<!ELEMENT keb (#PCDATA)>
<!ELEMENT ke_inf (#PCDATA)>
<!ELEMENT ke_pri (#PCDATA)>
<!ELEMENT r_ele (reb, re_nokanji?, re_restr*, re_inf*, re_pri*)>
<!ELEMENT reb (#PCDATA)>
<!ELEMENT re_nokanji (#PCDATA)>
<!ELEMENT re_restr (#PCDATA)>
<!ELEMENT re_inf (#PCDATA)>
<!ELEMENT re_pri (#PCDATA)>
<!ELEMENT sense (stagk*, stagr*, pos*, xref*, ant*, field*, misc*, s_inf*, lsource*, dial*, gloss*, example*)>
<!ELEMENT stagk (#PCDATA)>
<!ELEMENT stagr (#PCDATA)>
<!ELEMENT xref (#PCDATA)*>
<!ELEMENT ant (#PCDATA)*>
<!ELEMENT pos (#PCDATA)>
<!ELEMENT field (#PCDATA)>
<!ELEMENT misc (#PCDATA)>
<!ELEMENT lsource (#PCDATA)>
<!ATTLIST lsource xml:lang CDATA "eng">
<!ATTLIST lsource ls_type CDATA #IMPLIED>
<!ATTLIST lsource ls_wasei CDATA #IMPLIED>
<!ELEMENT dial (#PCDATA)>
<!ELEMENT gloss (#PCDATA | pri)*>
<!ATTLIST gloss xml:lang CDATA "eng">
<!ATTLIST gloss g_gend CDATA #IMPLIED>
<!ATTLIST gloss g_type CDATA #IMPLIED>
<!ELEMENT pri (#PCDATA)>
<!ELEMENT s_inf (#PCDATA)>
<!ELEMENT example (ex_srce,ex_text,ex_sent+)>
<!ELEMENT ex_srce (#PCDATA)>
<!ELEMENT ex_text (#PCDATA)>
<!ELEMENT ex_sent (#PCDATA)>
<!ATTLIST ex_sent xml:lang CDATA "eng">
<!ATTLIST ex_srce exsrc_type CDATA #IMPLIED>
<!ENTITY bra "Brazilian">
<!ENTITY hob "Hokkaido-ben">
<!ENTITY ksb "Kansai-ben">
<!ENTITY ktb "Kantou-ben">
<!ENTITY kyb "Kyoto-ben">
<!ENTITY kyu "Kyuushuu-ben">
<!ENTITY nab "Nagano-ben">
<!ENTITY osb "Osaka-ben">
<!ENTITY rkb "Ryuukyuu-ben">
<!ENTITY thb "Touhoku-ben">
<!ENTITY tsb "Tosa-ben">
<!ENTITY tsug "Tsugaru-ben">
<!ENTITY agric "agriculture">
<!ENTITY anat "anatomy">
<!ENTITY archeol "archeology">
<!ENTITY archit "architecture">
<!ENTITY art "art, aesthetics">
<!ENTITY astron "astronomy">
<!ENTITY audvid "audiovisual">
<!ENTITY aviat "aviation">
<!ENTITY baseb "baseball">
<!ENTITY biochem "biochemistry">
<!ENTITY biol "biology">
<!ENTITY bot "botany">
<!ENTITY boxing "boxing">
<!ENTITY Buddh "Buddhism">
<!ENTITY bus "business">
<!ENTITY cards "card games">
<!ENTITY chem "chemistry">
<!ENTITY chmyth "Chinese mythology">
<!ENTITY Christn "Christianity">
<!ENTITY civeng "civil engineering">
<!ENTITY cloth "clothing">
<!ENTITY comp "computing">
<!ENTITY cryst "crystallography">
<!ENTITY dent "dentistry">
<!ENTITY ecol "ecology">
<!ENTITY econ "economics">
<!ENTITY elec "electricity, elec. eng.">
<!ENTITY electr "electronics">
<!ENTITY embryo "embryology">
<!ENTITY engr "engineering">
<!ENTITY ent "entomology">
<!ENTITY figskt "figure skating">
<!ENTITY film "film">
<!ENTITY finc "finance">
<!ENTITY fish "fishing">
<!ENTITY food "food, cooking">
<!ENTITY gardn "gardening, horticulture">
<!ENTITY genet "genetics">
<!ENTITY geogr "geography">
<!ENTITY geol "geology">
<!ENTITY geom "geometry">
<!ENTITY go "go (game)">
<!ENTITY golf "golf">
<!ENTITY gramm "grammar">
<!ENTITY grmyth "Greek mythology">
<!ENTITY hanaf "hanafuda">
<!ENTITY horse "horse racing">
<!ENTITY internet "Internet">
<!ENTITY jpmyth "Japanese mythology">
<!ENTITY kabuki "kabuki">
<!ENTITY law "law">
<!ENTITY ling "linguistics">
<!ENTITY logic "logic">
<!ENTITY MA "martial arts">
<!ENTITY mahj "mahjong">
<!ENTITY manga "manga">
<!ENTITY math "mathematics">
<!ENTITY mech "mechanical engineering">
<!ENTITY med "medicine">
<!ENTITY met "meteorology">
<!ENTITY mil "military">
<!ENTITY min "mineralogy">
<!ENTITY mining "mining">
<!ENTITY motor "motorsport">
<!ENTITY music "music">
<!ENTITY noh "noh">
<!ENTITY ornith "ornithology">
<!ENTITY paleo "paleontology">
<!ENTITY pathol "pathology">
<!ENTITY pharm "pharmacology">
<!ENTITY phil "philosophy">
<!ENTITY photo "photography">
<!ENTITY physics "physics">
<!ENTITY physiol "physiology">
<!ENTITY politics "politics">
<!ENTITY print "printing">
<!ENTITY prowres "professional wrestling">
<!ENTITY psy "psychiatry">
<!ENTITY psyanal "psychoanalysis">
<!ENTITY psych "psychology">
<!ENTITY rail "railway">
<!ENTITY rommyth "Roman mythology">
<!ENTITY Shinto "Shinto">
<!ENTITY shogi "shogi">
<!ENTITY ski "skiing">
<!ENTITY sports "sports">
<!ENTITY stat "statistics">
<!ENTITY stockm "stock market">
<!ENTITY sumo "sumo">
<!ENTITY surg "surgery">
<!ENTITY telec "telecommunications">
<!ENTITY tradem "trademark">
<!ENTITY tv "television">
<!ENTITY vet "veterinary terms">
<!ENTITY vidg "video games">
<!ENTITY zool "zoology">
<!ENTITY ateji "ateji (phonetic) reading">
<!ENTITY ik "word containing irregular kana usage">
<!ENTITY iK "word containing irregular kanji usage">
<!ENTITY io "irregular okurigana usage">
<!ENTITY oK "word containing out-dated kanji or kanji usage">
<!ENTITY rK "rarely used kanji form">
<!ENTITY sK "search-only kanji form">
<!ENTITY abbr "abbreviation">
<!ENTITY arch "archaic">
<!ENTITY char "character">
<!ENTITY chn "children's language">
<!ENTITY col "colloquial">
<!ENTITY company "company name">
<!ENTITY creat "creature">
<!ENTITY dated "dated term">
<!ENTITY dei "deity">
<!ENTITY derog "derogatory">
<!ENTITY doc "document">
<!ENTITY euph "euphemistic">
<!ENTITY ev "event">
<!ENTITY fam "familiar language">
<!ENTITY fem "female term or language">
<!ENTITY fict "fiction">
<!ENTITY form "formal or literary term">
<!ENTITY given "given name or forename, gender not specified">
<!ENTITY group "group">
<!ENTITY hist "historical term">
<!ENTITY hon "honorific or respectful (sonkeigo) language">
<!ENTITY hum "humble (kenjougo) language">
<!ENTITY id "idiomatic expression">
<!ENTITY joc "jocular, humorous term">
<!ENTITY leg "legend">
<!ENTITY m-sl "manga slang">
<!ENTITY male "male term or language">
<!ENTITY myth "mythology">
<!ENTITY net-sl "Internet slang">
<!ENTITY obj "object">
<!ENTITY obs "obsolete term">
<!ENTITY on-mim "onomatopoeic or mimetic word">
<!ENTITY organization "organization name">
<!ENTITY oth "other">
<!ENTITY person "full name of a particular person">
<!ENTITY place "place name">
<!ENTITY poet "poetical term">
<!ENTITY pol "polite (teineigo) language">
<!ENTITY product "product name">
<!ENTITY proverb "proverb">
<!ENTITY quote "quotation">
<!ENTITY rare "rare term">
<!ENTITY relig "religion">
<!ENTITY sens "sensitive">
<!ENTITY serv "service">
<!ENTITY ship "ship name">
<!ENTITY sl "slang">
<!ENTITY station "railway station">
<!ENTITY surname "family or surname">
<!ENTITY uk "word usually written using kana alone">
<!ENTITY unclass "unclassified name">
<!ENTITY vulg "vulgar expression or word">
<!ENTITY work "work of art, literature, music, etc. name">
<!ENTITY X "rude or X-rated term (not displayed in educational software)">
<!ENTITY yoji "yojijukugo">
<!ENTITY adj-f "noun or verb acting prenominally">
<!ENTITY adj-i "adjective (keiyoushi)">
<!ENTITY adj-ix "adjective (keiyoushi) - yoi/ii class">
<!ENTITY adj-kari "'kari' adjective (archaic)">
<!ENTITY adj-ku "'ku' adjective (archaic)">
<!ENTITY adj-na "adjectival nouns or quasi-adjectives (keiyodoshi)">
<!ENTITY adj-nari "archaic/formal form of na-adjective">
<!ENTITY adj-no "nouns which may take the genitive case particle 'no'">
<!ENTITY adj-pn "pre-noun adjectival (rentaishi)">
<!ENTITY adj-shiku "'shiku' adjective (archaic)">
<!ENTITY adj-t "'taru' adjective">
<!ENTITY adv "adverb (fukushi)">
<!ENTITY adv-to "adverb taking the 'to' particle">
<!ENTITY aux "auxiliary">
<!ENTITY aux-adj "auxiliary adjective">
<!ENTITY aux-v "auxiliary verb">
<!ENTITY conj "conjunction">
<!ENTITY cop "copula">
<!ENTITY ctr "counter">
<!ENTITY exp "expressions (phrases, clauses, etc.)">
<!ENTITY int "interjection (kandoushi)">
<!ENTITY n "noun (common) (futsuumeishi)">
<!ENTITY n-adv "adverbial noun (fukushitekimeishi)">
<!ENTITY n-pr "proper noun">
<!ENTITY n-pref "noun, used as a prefix">
<!ENTITY n-suf "noun, used as a suffix">
<!ENTITY n-t "noun (temporal) (jisoumeishi)">
<!ENTITY num "numeric">
<!ENTITY pn "pronoun">
<!ENTITY pref "prefix">
<!ENTITY prt "particle">
<!ENTITY suf "suffix">
<!ENTITY unc "unclassified">
<!ENTITY v-unspec "verb unspecified">
<!ENTITY v1 "Ichidan verb">
<!ENTITY v1-s "Ichidan verb - kureru special class">
<!ENTITY v2a-s "Nidan verb with 'u' ending (archaic)">
<!ENTITY v2b-k "Nidan verb (upper class) with 'bu' ending (archaic)">
<!ENTITY v2b-s "Nidan verb (lower class) with 'bu' ending (archaic)">
<!ENTITY v2d-k "Nidan verb (upper class) with 'dzu' ending (archaic)">
<!ENTITY v2d-s "Nidan verb (lower class) with 'dzu' ending (archaic)">
<!ENTITY v2g-k "Nidan verb (upper class) with 'gu' ending (archaic)">
<!ENTITY v2g-s "Nidan verb (lower class) with 'gu' ending (archaic)">
<!ENTITY v2h-k "Nidan verb (upper class) with 'hu/fu' ending (archaic)">
<!ENTITY v2h-s "Nidan verb (lower class) with 'hu/fu' ending (archaic)">
<!ENTITY v2k-k "Nidan verb (upper class) with 'ku' ending (archaic)">
<!ENTITY v2k-s "Nidan verb (lower class) with 'ku' ending (archaic)">
<!ENTITY v2m-k "Nidan verb (upper class) with 'mu' ending (archaic)">
<!ENTITY v2m-s "Nidan verb (lower class) with 'mu' ending (archaic)">
<!ENTITY v2n-s "Nidan verb (lower class) with 'nu' ending (archaic)">
<!ENTITY v2r-k "Nidan verb (upper class) with 'ru' ending (archaic)">
<!ENTITY v2r-s "Nidan verb (lower class) with 'ru' ending (archaic)">
<!ENTITY v2s-s "Nidan verb (lower class) with 'su' ending (archaic)">
<!ENTITY v2t-k "Nidan verb (upper class) with 'tsu' ending (archaic)">
<!ENTITY v2t-s "Nidan verb (lower class) with 'tsu' ending (archaic)">
<!ENTITY v2w-s "Nidan verb (lower class) with 'u' ending and 'we' conjugation (archaic)">
<!ENTITY v2y-k "Nidan verb (upper class) with 'yu' ending (archaic)">
<!ENTITY v2y-s "Nidan verb (lower class) with 'yu' ending (archaic)">
<!ENTITY v2z-s "Nidan verb (lower class) with 'zu' ending (archaic)">
<!ENTITY v4b "Yodan verb with 'bu' ending (archaic)">
<!ENTITY v4g "Yodan verb with 'gu' ending (archaic)">
<!ENTITY v4h "Yodan verb with 'hu/fu' ending (archaic)">
<!ENTITY v4k "Yodan verb with 'ku' ending (archaic)">
<!ENTITY v4m "Yodan verb with 'mu' ending (archaic)">
<!ENTITY v4n "Yodan verb with 'nu' ending (archaic)">
<!ENTITY v4r "Yodan verb with 'ru' ending (archaic)">
<!ENTITY v4s "Yodan verb with 'su' ending (archaic)">
<!ENTITY v4t "Yodan verb with 'tsu' ending (archaic)">
<!ENTITY v5aru "Godan verb - -aru special class">
<!ENTITY v5b "Godan verb with 'bu' ending">
<!ENTITY v5g "Godan verb with 'gu' ending">
<!ENTITY v5k "Godan verb with 'ku' ending">
<!ENTITY v5k-s "Godan verb - Iku/Yuku special class">
<!ENTITY v5m "Godan verb with 'mu' ending">
<!ENTITY v5n "Godan verb with 'nu' ending">
<!ENTITY v5r "Godan verb with 'ru' ending">
<!ENTITY v5r-i "Godan verb with 'ru' ending (irregular verb)">
<!ENTITY v5s "Godan verb with 'su' ending">
<!ENTITY v5t "Godan verb with 'tsu' ending">
<!ENTITY v5u "Godan verb with 'u' ending">
<!ENTITY v5u-s "Godan verb with 'u' ending (special class)">
<!ENTITY v5uru "Godan verb - Uru old class verb (old form of Eru)">
<!ENTITY vi "intransitive verb">
<!ENTITY vk "Kuru verb - special class">
<!ENTITY vn "irregular nu verb">
<!ENTITY vr "irregular ru verb, plain form ends with -ri">
<!ENTITY vs "noun or participle which takes the aux. verb suru">
<!ENTITY vs-c "su verb - precursor to the modern suru">
<!ENTITY vs-i "suru verb - included">
<!ENTITY vs-s "suru verb - special class">
<!ENTITY vt "transitive verb">
<!ENTITY vz "Ichidan verb - zuru verb (alternative form of -jiru verbs)">
<!ENTITY gikun "gikun (meaning as reading) or jukujikun (special kanji reading)">
<!ENTITY ik "word containing irregular kana usage">
<!ENTITY ok "out-dated or obsolete kana usage">
<!ENTITY rk "rarely used kana form">
<!ENTITY sk "search-only kana form">

=== xAkre/jmdict.js/src/__tests__/data/xml/fullDataEntry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JMdict SYSTEM "./originalDtd.dtd">
<JMdict>
    <entry>
        <ent_seq>100</ent_seq>
        <k_ele>
            <keb>日本</keb>
            <ke_inf>Some additional information</ke_inf>
            <ke_inf>Some other additional information</ke_inf>
            <ke_pri>ichi1</ke_pri>
            <ke_pri>news1</ke_pri>
        </k_ele>
        <r_ele>
            <reb>にほん</reb>
            <re_nokanji />
            <re_restr>日本</re_restr>
            <re_inf>Some additional information</re_inf>
            <re_inf>Some other additional information</re_inf>
            <re_pri>ichi1</re_pri>
            <re_pri>news1</re_pri>
        </r_ele>
        <sense>
            <pos>&n;</pos>
            <pos>&adj-i;</pos>
            <xref>word</xref>
            <xref>word・reading</xref>
            <xref>word・1</xref>
            <xref>word・reading・1</xref>
            <ant>Antonym</ant>
            <ant>Another antonym</ant>
            <field>&biol;</field>
            <field>&biochem;</field>
            <misc>Some misc information</misc>
            <misc>Some other misc information</misc>
            <s_inf>Some additional information</s_inf>
            <s_inf>Some other additional information</s_inf>
            <lsource xml:lang="eng">Source</lsource>
            <lsource xml:lang="fra">Source</lsource>
            <lsource xml:lang="ger" ls_type="part">Source</lsource>
            <lsource xml:lang="dut" ls_type="part" ls_wasei="y">Source</lsource>
            <dial>&hob;</dial>
            <dial>&ksb;</dial>
            <gloss xml:lang="eng">Japan</gloss>
            <gloss xml:lang="rus">Japan</gloss>
            <gloss xml:lang="dut" g_gend="feminine">Japan</gloss>
            <gloss xml:lang="fra" g_gend="masculine" g_type="tm">Japan</gloss>
        </sense>
    </entry>
</JMdict>
